version: '3.8'
services:
  backend:
    build:
      context: ./backend-module
      dockerfile: Dockerfile
    image: bipapp-backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
    restart: unless-stopped
